name: provenance-dev
channels:
    - conda-forge
dependencies:
- python==3.5
- ipython
- numpy
- pandas
- alembic
- numpydoc
- sphinx
- pandoc
- pip:
  - versioneer
  - twine
  - nbsphinx
  - yamlmagic
  - sphinxcontrib-websupport
  - sphinx-autobuild
