name: code-style

on:
  push:
    branches: "*"
  pull_request:
    branches: trunk

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Lint via pre-commit checks
        uses: pre-commit/action@v2.0.0
